apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy-namespace-custom
  namespace: custom-policies
  annotations:
    policy.mcm.ibm.com/standards: 
    policy.mcm.ibm.com/categories: 
    policy.mcm.ibm.com/controls: 
spec:
  complianceType: musthave
  remediationAction: enforce
  disabled: false
  object-templates:
    - complianceType: musthave
      objectDefinition:
        kind: Namespace 
        apiVersion: v1
        metadata:
          name: project-one
    - complianceType: mustnothave
      objectDefinition:
        kind: Namespace 
        apiVersion: v1
        metadata:
          name: project-two